[[services]]
name = "frontend"
source = "."
[services.build]
builder = "dockerfile"
dockerfile = "docker/Dockerfile.frontend"

[[services]]
name = "websocket"
source = "."
[services.build]
builder = "dockerfile"
dockerfile = "docker/Dockerfile.websocket"